### ISSUE TITLE
Add cli command lines for managing the projects.

### ISSUE THREAD

**Issue by yaredtsy** [yaredtsy/node-express-starter-kit#10]
**Resource**
https://medium.com/@manavshrivastava/lets-build-a-cli-command-line-interface-with-node-js-d3b5faacc5ea

**Tasks**

- [ ] user should be able to create new projects
- [ ] user should be able to create apps
- [ ] user should have a choice for a simple crud template . 
- [ ] generated a simple test template for modules
